config/routes.rb
Rails.application.routes.draw do
  resources :shapes
  resources :sizes
  resources :products
get 'calculate' => 'products#suggestions', :as => :suggestions
  root 'products#welcome'

end

app/models/product.rb
class Product < ActiveRecord::Base

belongs_to :shape

has_attached_file :avatar, styles: { medium: "383x526>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

end

app/models/shape.rb
class Shape < ActiveRecord::Base
has_many :products
has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\Z/

end

app/models/size.rb
class Size < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  include ProductsHelper 
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  def welcome
    @products = Product.limit(6).order("RANDOM()")
    @product = Product.new
  end

 def suggestions
  #llamar el método que cree de shapes
    
    @shape = get_shape(params[:shoulder], params[:waist], params[:hips])
    if !@shape.nil?
    shape_object =  Shape.where(:name => @shape)
    shape_id = shape_object.first.id
    @products = Product.where(:shape_id => shape_id)
    @shape_avatar = shape_object.first.avatar
    @shape_description = shape_object.first.description
    end
  
  end


  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :color, :price, :shape_id, :avatar)
    end
end

app/controllers/shapes_controller.rb
class ShapesController < ApplicationController
  before_action :set_shape, only: [:show, :edit, :update, :destroy]

  # GET /shapes
  # GET /shapes.json
  def index
    @shapes = Shape.all
  end

  # GET /shapes/1
  # GET /shapes/1.json
  def show
  end

  # GET /shapes/new
  def new
    @shape = Shape.new
  end

  # GET /shapes/1/edit
  def edit
  end

  # POST /shapes
  # POST /shapes.json
  def create
    @shape = Shape.new(shape_params)

    respond_to do |format|
      if @shape.save
        format.html { redirect_to @shape, notice: 'Shape was successfully created.' }
        format.json { render :show, status: :created, location: @shape }
      else
        format.html { render :new }
        format.json { render json: @shape.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shapes/1
  # PATCH/PUT /shapes/1.json
  def update
    respond_to do |format|
      if @shape.update(shape_params)
        format.html { redirect_to @shape, notice: 'Shape was successfully updated.' }
        format.json { render :show, status: :ok, location: @shape }
      else
        format.html { render :edit }
        format.json { render json: @shape.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shapes/1
  # DELETE /shapes/1.json
  def destroy
    @shape.destroy
    respond_to do |format|
      format.html { redirect_to shapes_url, notice: 'Shape was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shape
      @shape = Shape.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shape_params
      params.require(:shape).permit(:name, :avatar, :description)
    end
end

app/controllers/sizes_controller.rb
class SizesController < ApplicationController
  before_action :set_size, only: [:show, :edit, :update, :destroy]

  # GET /sizes
  # GET /sizes.json
  def index
    @sizes = Size.all
  end

  # GET /sizes/1
  # GET /sizes/1.json
  def show
  end

  # GET /sizes/new
  def new
    @size = Size.new
  end

  # GET /sizes/1/edit
  def edit
  end

  # POST /sizes
  # POST /sizes.json
  def create
    @size = Size.new(size_params)

    respond_to do |format|
      if @size.save
        format.html { redirect_to @size, notice: 'Size was successfully created.' }
        format.json { render :show, status: :created, location: @size }
      else
        format.html { render :new }
        format.json { render json: @size.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sizes/1
  # PATCH/PUT /sizes/1.json
  def update
    respond_to do |format|
      if @size.update(size_params)
        format.html { redirect_to @size, notice: 'Size was successfully updated.' }
        format.json { render :show, status: :ok, location: @size }
      else
        format.html { render :edit }
        format.json { render json: @size.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sizes/1
  # DELETE /sizes/1.json
  def destroy
    @size.destroy
    respond_to do |format|
      format.html { redirect_to sizes_url, notice: 'Size was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_size
      @size = Size.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def size_params
      params.require(:size).permit(:product_id, :stock, :shape_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/products_helper.rb
module ProductsHelper

def get_shape(shoulder, waist, hips)

	shape = nil
	
	a = shoulder.to_f - waist.to_f
	b = hips.to_f - waist.to_f
	c = shoulder.to_f/hips.to_f

if (c>=0.90 && c< 1.03 && a>=30 && a<40 && b>=30 && b<40)
	
	shape = "Hourglass"

elsif (c<1 )

	shape = "Triangle"
	
elsif (c>1)
	
	shape = "Inverted Triangle"
	
else 
	
	shape= nil

end
puts shape
shape
end


end

app/helpers/shapes_helper.rb
module ShapesHelper
end

app/helpers/sizes_helper.rb
module SizesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Silhouette Store</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<%= javascript_include_tag 'application', media: 'all' %>
<%= javascript_include_tag 'sweetalert.min.js' %>


<link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700' rel='stylesheet' type='text/css'>

<link href='https://fonts.googleapis.com/css?family=Allura' rel='stylesheet' type='text/css'>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css" integrity="sha384-aUGj/X2zp5rLCbBxumKTCw2Z50WgIr1vs/PFN4praOTvYXWlVyh2UtNUU0KAUhAX" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>

</head>
<body>

<%= yield %>

</body>
</html>

app/views/products/_form.html.erb
<%= form_for(@product, html: { multipart: true } ) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= f.file_field :avatar %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :color %><br>
    <%= f.text_field :color %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :shape_id %><br>
    <%= collection_select(:product, :shape_id, Shape.all, :id, :name,{ :prompt => 'Select a shape' }) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>
<div class="panel panel-default">
  <div class="panel-heading">Products</div></div>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Color</th>
      <th>Price</th>
      <th>Shape</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.description %></td>
        <td><%= product.color %></td>
        <td><%= product.price %></td>
        <td><%= !product.shape.nil? ? product.shape.name : "No Shape" %></td>
        <td><%= image_tag product.avatar.url(:thumb) %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'New Product', new_product_path, :class => "btn btn-info" %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Color:</strong>
  <%= @product.color %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<%= image_tag @product.avatar.url(:thumb) %>


<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/products/suggestions.html.erb
<div id="header">
    <div class="row">
          <div class="col-xs-3 col-sm-2">
            <div class="logo">
              <%= image_tag "silhouette_logo.png" %>
            </div>
          </div>

          <div class="col-xs-9 col-sm-6">
            <nav id="nav">
              <ul id="main-menu">
                <li><a href="#">Coats</a></li>
                <li><a href="#">Dresses</a></li>
                <li><a href="#">Shorts</a></li>
                <li><a href="#">Skirts</a></li>
                <li><a href="#">Tops</a></li>
                <li><a href="#">Trousers</a></li>
              </ul>
            </nav>          
          </div>

          <div class="col-xs-3 col-sm-2">
            <div class="social">
              <ul>
                <li>
              <%= link_to image_tag('facebook.png'), "https://facebook.com", target: '_blank' %>
            </li>
                <li>
                  <%= link_to image_tag('instagram.png'), "https://instagram.com", target: '_blank' %>
                </li>
                <li>
                  <%= link_to image_tag('pinterest.png'), "https://pinterest.com", target: '_blank' %>
                </li>
                <li>
                  <%= link_to image_tag('youtube.png'), "https://youtube.com", target: '_blank' %>
                </li>
                <li>
                  <%= link_to image_tag('twitter.png'), "https://twitter.com", target: '_blank' %>
                </li>
                <li>
                  <%= link_to image_tag('gplus.png'), "https://plus.google.com", target: '_blank' %>
                </li>           
            </div>
            
          </div>

          <div class="col-xs-3 col-sm-2">
            <nav id="subnav">
              <ul>
                <li><a href="#">LOGIN |</a></li>
                <li><a href="#">SIGN UP</a></li>
                <li><%= link_to image_tag('bag.png'), "#" %></li>
              </ul>
            </nav>          
          </div>
      </div>
</div>


<div class="wrapper-res">      
  <div class="row-res">

      <div>
        <%if  !@shape.nil? %>
        <p>Your Silhouette is <%= @shape %></p> 
      </div>
      <div>
        <div class="shape-res">
          <%= image_tag @shape_avatar.url(:medium)%>
        </div>
        <div class="shape-desc">
          <%= @shape_description%>
        </div>
      </div>
            
    <% @products.each do |product| %>

    <div class="col-xs-6 col-sm-3">  
      <div class="items-res">
        <div class="item-image-res"><%= image_tag product.avatar.url%></div>
        <div class="item-name-res"><%=product.name%></div>
        <div class="item-desc"><%=product.description%></div>
        <div class="item-price-res"><%=number_to_currency(product.price)%></div>
        <div class="item-add-res">ADD TO BAG</div>
      </div>
    </div>  
    
    <%end%>

    <% else %>
      <h1> We can not identify your body Silhouette </h1>
      <div class="calc-btn-res">
      <%= link_to("Try it again!", :root) %>
      </div>
    <%end%>

  </div>
</div>

<footer>
    <div class="footer-store">
      <div class="row">
        <div class="col-xs-6 col-sm-3">
          <div class="logo-foot">
                <%= image_tag "silhouette_logo_white.png" %>
              </div>
              <div class="contact">
                <ul>
                  <li>contactus@silhouettestore.com</li>
                  <li>+1 (800) 687-2742</li>
                </ul>
              </div>
        </div>
        <div class="col-xs-6 col-sm-3">
          <div class="menu-foot">
                <ul>
                  <li>Coats</li>
                  <li>Dresses</li>
                  <li>Shorts</li>
                  <li>Skirts</li>
                  <li>Tops</li>
                  <li>Trousers</li>
                </ul>
              </div>
        </div>
        <div class="col-xs-6 col-sm-3">
          <div class="terms">
            <ul>
              <li>Privacy and Cookies</li>
                  <li>Terms and Conditions</li>
                  <li>About Us</li>             
            </ul>         
          </div>
        </div>
        <div class="col-xs-6 col-sm-3">
          <div class="news">
            <ul>
              <li>Subscribe for Silhouette News</li>
            </ul>
            <div class="news-box">
              Your e-mail address
            </div>
            <div class="credit-cards">
              <%= image_tag "credit-cards.png" %>
            </div>
            <div class="social-foot">
              <ul>
                    <li>
                  <%= link_to image_tag('facebook-foot.png'), "https://facebook.com", target: '_blank' %>
                </li>
                    <li>
                      <%= link_to image_tag('instagram-foot.png'), "https://instagram.com", target: '_blank' %>
                    </li>
                    <li>
                      <%= link_to image_tag('pinterest-foot.png'), "https://pinterest.com", target: '_blank' %>
                    </li>
                    <li>
                      <%= link_to image_tag('youtube-foot.png'), "https://youtube.com", target: '_blank' %>
                    </li>
                    <li>
                      <%= link_to image_tag('twitter-foot.png'), "https://twitter.com", target: '_blank' %>
                    </li>
                    <li>
                      <%= link_to image_tag('gplus-foot.png'), "https://plus.google.com", target: '_blank' %>
                    </li>
                  </ul> 
            </div>
          </div>
        </div>

      </div>
    </div>
  </footer>

app/views/shapes/_form.html.erb
<%= form_for(@shape, html: { multipart: true }) do |f| %>
  <% if @shape.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shape.errors.count, "error") %> prohibited this shape from being saved:</h2>
      
      <ul>
      <% @shape.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<%= f.file_field :avatar %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
<div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shapes/edit.html.erb
<h1>Editing Shape</h1>

<%= render 'form' %>

<%= link_to 'Show', @shape %> |
<%= link_to 'Back', shapes_path %>

app/views/shapes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Shapes</h1>

<div class="panel panel-default">
  <div class="panel-heading">Shapes</div></div>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shapes.each do |shape| %>
      <tr>
        <td><%= shape.name %></td>
        <td><%= shape.description %></td>
        <td><%= image_tag shape.avatar.url(:thumb)%></td>
        <td><%= link_to 'Show', shape %></td>
        <td><%= link_to 'Edit', edit_shape_path(shape) %></td>
        <td><%= link_to 'Destroy', shape, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shape', new_shape_path, :class => "btn btn-info" %>

app/views/shapes/new.html.erb
<h1>New Shape</h1>

<%= render 'form' %>

<%= link_to 'Back', shapes_path %>

app/views/shapes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @shape.name %>
</p>

<%= link_to 'Edit', edit_shape_path(@shape) %> |
<%= link_to 'Back', shapes_path %>

app/views/sizes/_form.html.erb
<%= form_for(@size) do |f| %>
  <% if @size.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@size.errors.count, "error") %> prohibited this size from being saved:</h2>

      <ul>
      <% @size.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :stock %><br>
    <%= f.number_field :stock %>
  </div>
  <div class="field">
    <%= f.label :shape_id %><br>
    <%= f.number_field :shape_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sizes/edit.html.erb
<h1>Editing Size</h1>

<%= render 'form' %>

<%= link_to 'Show', @size %> |
<%= link_to 'Back', sizes_path %>

app/views/sizes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sizes</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Stock</th>
      <th>Shape</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sizes.each do |size| %>
      <tr>
        <td><%= size.product_id %></td>
        <td><%= size.stock %></td>
        <td><%= size.shape_id %></td>
        <td><%= link_to 'Show', size %></td>
        <td><%= link_to 'Edit', edit_size_path(size) %></td>
        <td><%= link_to 'Destroy', size, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Size', new_size_path %>

app/views/sizes/new.html.erb
<h1>New Size</h1>

<%= render 'form' %>

<%= link_to 'Back', sizes_path %>

app/views/sizes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @size.product_id %>
</p>

<p>
  <strong>Stock:</strong>
  <%= @size.stock %>
</p>

<p>
  <strong>Shape:</strong>
  <%= @size.shape_id %>
</p>

<%= link_to 'Edit', edit_size_path(@size) %> |
<%= link_to 'Back', sizes_path %>